### ISSUE TITLE
I have a problem about glBufferSubData.

### ISSUE THREAD

**Issue by HWTsang** [Rabbid76/graphics-snippets#4]
Hi, how you doing? Your python code help me a lot. I encountered some difficulties in learning opengl. I think your answer will solve my problem.Please help me. thanks.
https://stackoverflow.com/questions/68572255/why-opengl-show-nothing-with-glfw-and-glbuffersubdata/68577689?noredirect=1#comment121209696_68577689

**Comment by HWTsang** [comment]
thanks for your reply.  └(^o^)┘

**Comment by Rabbid76** [comment]
This has nothing to do with this repository. Why do you spam this here?
